name: dbt_ci_pipeline
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
on:
  push:
    branches:
      - main

permissions:
  content: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  dbt_test_job:
    runs-on: ubuntu-latest
    environment: snowflake_trial

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt-snowflake
        run: |
          pip install --upgrade pip
          pip install dbt-snowflake
        
      - name: Install dbt dependencies
        run: dbt deps
    
      - name: Set up dbt profiles.yml 
        run: |
          mkdir -p ~/.dbt 
          cat << 'EOF' > ~/.dbt/profiles.yml 
          olist_analytics:
            outputs:
              ci_target:
                type: snowflake
                account: ${{ secrets.SF_ACCOUNT }}
                user: ${{ secrets.SF_USER }}
                password: ${{ secrets.SF_PASSWORD }}
                role: ${{ secrets.SF_ROLE }}
                warehouse: ${{ secrets.SF_WAREHOUSE }}
                database: KAGGLE_OLIST_DEV
                schema: DBT_DEV
            target: ci_target
          EOF
    
      - name: Run dbt test
        run: dbt test

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - Generate dbt Docs
        run: |
          dbt docs generate --profiles-dir .
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './target'
    
      - name: Deploy to Girhub Pages
        id: deployment
        uses: actions/deploy-pages@v4