name: dbt_ci_pipeline

on:
  push:
    branches:
      - main

jobs:
  dbt_test_job:
    runs_on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dbt-snowflake
        run: |
          pip install --upgrade pip
          pip install dbt-snowflake
        
      - name: Install dbt dependencies
        run: dbt deps
    
      - name: Set up dbt profiles.yml 
        run: |
          mkdir -p ~/.dbt 
          cat <<EOF>> ~/.dbt/profiles.yml 
          olist_cohort_analytics_dbt:
            outputs:
              ci_target:
                type: snowflake
                account: ${{secrets.SF_ACCOUNT}}
                user: ${{secrets.SF_USER}}
                password: ${{secrets.SF_PASSWORD}}
                role: ${{secrets.SF_ROLE}}
                warehouse: ${{secrets.SF_WAREHOUSE}}
                database: KAGGLE_OLIST_DEV
                schema: DBT_DEV
            target: ci_target
          EOF
    
      - name: Run dbt test
        run: dbt test